---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  tags: logstash_install

- include: config.yml
  tags: logstash_config

- name: Logstash start at boot time
  service:
    name=logstash
    state=started
    enabled=yes

# vi:ts=2:sw=2:et:ft=yaml
